### ISSUE TITLE
UnknownErrorException: The reference does not point to a /Page dictionary

### ISSUE THREAD

**Issue by crystalfp** [lublak/pdfdataextract#3]
**Describe the bug**
Some PDF files generate an exception in `PdfData.extract(dataBuffer);` even when info and metadata are visible inside Acrobat Reader. The exception is:
```
Error: UnknownErrorException: The reference does not point to a /Page dictionary.
    at D:\Projects\AMDIdeaIgniterEnvironment\exp\node_modules\pdfjs-dist\legacy\build\pdf.js:11309:31
    at async getPageNumber (D:\Projects\AMDIdeaIgniterEnvironment\exp\node_modules\pdfdataextract\dist\pdfdataextractor.js:10:18)
    at async parseOutline (D:\Projects\AMDIdeaIgniterEnvironment\exp\node_modules\pdfdataextract\dist\pdfdataextractor.js:31:23)
    at async Function.extract (D:\Projects\AMDIdeaIgniterEnvironment\exp\node_modules\pdfdataextract\dist\pdfdata.js:52:378)
```
The code is the one from the README file.

**Expected behavior**
If info and metadata exists and are visible in Adobe Reader, should be accessible from the library.

**Environment (please complete the following information):**
 - OS: Windows 10 64bits
 - Node.js Version 16.3.0

**Additional context**
GitHub refuses to past here the pdf file and the screenshots, so here are under my Dropbox:
[The PDF file](https://www.dropbox.com/s/jrvjavfvrst6xm2/Dehaene-spelke-2015.pdf?dl=0)
[The info in acrobat](https://www.dropbox.com/s/pbe67v2dd77lv2y/Screenshot%202021-06-15%20040834.png?dl=0)
[The metadata](https://www.dropbox.com/s/jeotfbdrtu4wvfp/Screenshot%202021-06-15%20040920.png?dl=0)

**Comment by crystalfp** [comment]
BTW, calling directly PDF.js with the example [here](https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js) gives no error.

**Comment by lublak** [comment]
@crystalfp thank you for your bug report. i rewrite the outline parsing and it should now work.
If the problem is not solved or another problem arises, please contact me again.
The new version should be public on npm soon.
