### ISSUE TITLE
Handling of ligatures

### ISSUE THREAD

**Issue by florianbepunkt** [lublak/pdfdataextract#5]
**Describe the bug**
Ligatures are incorrectly parsed. I can't type ligatures in markdown, but a PDF line with the code `&LBFY68Dd6fb884c` (with a ligature of fb) is parsed as `&LBFY68Dd6\"884c`

![Bildschirmfoto 2021-07-31 um 11 44 24](https://user-images.githubusercontent.com/8314202/127735950-b107b26a-20b4-42f8-9b4d-135c9e1c2cbb.png)

**Expected behavior**
Ligatures should be parsed to regular characters, ligature fb should be parsed as fb

**Environment (please complete the following information):**
 - OS: OSX 10.15.7
 - Node.js Version v14.15.4

**Additional context**
Not sure if all fonts encode ligatures the same way

**Comment by lublak** [comment]
@florianbepunkt hi and thank you for your bug report,
do you happen to have a pdf file that you can make available to me?

**Comment by lublak** [comment]
@florianbepunkt is this issue still significant for you? Currently it is difficult for me to understand it. So again the question if you have a pdf file for me or how I can cause this problem myself.

**Comment by florianbepunkt** [comment]
@lublak Sorry for the late reply. I investigated this further today. It seems that the problem is either with my PDF or the embedded font encoding, not with this library per se. Sorry for the fuss.
